### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by FlockrushAdmin** [riodda/alpaca-trading-bot#1]
Hi Dario,

Wanted to better understand what you wrote, if you can give an example like:

First BUY @ 25
Second BUY @ ?
Third BUY @ ?
Fourth BUY @ ?

This was what you wrote. Thank you!!! Have an amazing day!

Hi guys, really thanks for this great open source project !
I would like to really give me opinion on postion stacking or DCA, I come from 2 years of trading in this way and i have to say that position stacking or DCA is in
credibly profitable for cryptos that have very good ups and downs. I would really encourage the community to have a position stacking feature.
I think that just enabling a newer buy when a newer buy signal is received would make the trick.
Also another important aspect is position scaling like:
base buy is 10, scaling factor is 1.1 so:

First buy signal is postion is open with10,
Second buy signal Position is increased by 10*1.1 so the new position ia 21.1
Third buy signal the potition is increased by (21.1+10)*1.1 and so on....
Then a table of the coefficent for the position is needed as well like:

BUY COEFF
1 1.1
2 1.1
3 1.1
....
7 1.1
8 0.25
9 0

**Comment by riodda** [comment]
Hi, the bot will only execute trades received from webhooks, the TV strategy or other strategies that you will use will have to calculate the DCA.

**Comment by FlockrushAdmin** [comment]
Thank you for getting back. I wanted to know what is the exact trigger logic for the buy downs. I am coding a module to handle it automatically and needed clarification. 

It would really help if you can fill the following and I will be golden:

if you can give an example like:

First BUY @ 25
Second BUY @ ?
Third BUY @ ?
Fourth BUY @ ?

my email is admin@surfable.io if you prefer.
